"""Create readable layouts from the manuscript's numeric table sources.

This script changes presentation, not the rounded numerical cells.  Wide tables are
split into panels; long tables are allowed to span pages instead of being clipped.
Run after make_revision_tables.py, make_tables.py and make_v2_tables.py.
"""
from pathlib import Path
import json
import re

ROOT = Path(__file__).resolve().parents[1]
PAPER = ROOT / "paper"


def rows(name):
    text = (PAPER / name).read_text(encoding="utf-8")
    body = text.split(r"\midrule", 1)[1].split(r"\bottomrule", 1)[0]
    return [[c.strip() for c in ln.strip().removesuffix(r"\\").split(" & ")]
            for ln in body.splitlines() if " & " in ln]


def write(name, text):
    (PAPER / name).write_text("% Generated by code/format_publication_tables.py; numerical cells preserved.\n" + text,
                             encoding="utf-8")


def tab(cols, header, data, size=9, sep=3):
    return ("{\\fontsize{" + str(size) + "}{" + str(size+2) + "}\\selectfont\n"
            "\\setlength{\\tabcolsep}{" + str(sep) + "pt}\n"
            "\\begin{tabular}{" + cols + "}\n\\toprule\n" + " & ".join(header)
            + " \\\\\n\\midrule\n" + "".join(" & ".join(r) + " \\\\\n" for r in data)
            + "\\bottomrule\n\\end{tabular}}\n")


def stack(value):
    return r"\shortstack{" + value.replace(" / ", r"\\") + "}" if " / " in value else value


def short(name):
    return {"isotropic kernel": "isotropic kernel", "network + residual kernel": "network + residual",
            "ensemble + residual kernel": "ensemble + residual", "kernel on features": "feature kernel",
            "kernel on concatenated features": "concatenated features",
            "coordinatewise selection": "coordinate selection", "network ensemble": "network ensemble"}.get(name, name)


def longtab(cols, header, data, caption, label, size=9, landscape=False):
    n = len(header)
    head = " & ".join(header) + " \\\\\n"
    text = (r"\clearpage" + "\n" + ("\\begin{landscape}\n" if landscape else "")
            + "{\\fontsize{" + str(size) + "}{" + str(size+2) + "}\\selectfont\n"
            + "\\setlength{\\tabcolsep}{4pt}\n\\setlength{\\LTcapwidth}{0.95\\linewidth}\n"
            + "\\begin{longtable}{" + cols + "}\n"
            + "\\caption{" + caption + "}\\label{" + label + "}\\\\\n"
            + "\\toprule\n" + head + "\\midrule\n\\endfirsthead\n"
            + "\\multicolumn{" + str(n) + "}{l}{\\tablename\\ \\thetable\\ (continued)}\\\\\n"
            + "\\toprule\n" + head + "\\midrule\n\\endhead\n"
            + "\\midrule\n\\multicolumn{" + str(n) + "}{r}{Continued on next page}\\\\\n\\endfoot\n"
            + "\\bottomrule\n\\endlastfoot\n"
            + "".join(" & ".join(r) + " \\\\\n" for r in data)
            + "\\end{longtable}}\n" + ("\\end{landscape}\n" if landscape else ""))
    return text


def main():
    rr = rows("table_v2_transmission.tex")
    a = [[short(r[0]),r[1],r[2],stack(r[3]),stack(r[4])] for r in rr]
    b = [[short(r[0]),stack(r[5]),r[6],r[7],r[8]] for r in rr]
    write("layout_v2_transmission.tex", r"\textbf{A. Errors and finite-range profiles}\par\medskip"+"\n"+
          tab("lrrrr", ["head", r"$\varepsilon_R$",r"$2\nu$ (fit)",r"\thead{raw p95\\raw p99}",r"\thead{constrained p95\\constrained p99}"],a)
          + r"\par\bigskip\textbf{B. Failure counts and bound diagnostics}\par\medskip"+"\n"+
          tab("lrrrr",["head",r"\thead{failure [\%]\\upper clip [\%]}",r"\thead{$\E\min\{R^2,$\\$e_R^2/t^2\}$}",r"\thead{violations\\on $s\le S$}",r"\thead{diagnostic\\bound / MSE}"],b))
    rr=rows("table_v2_replication.tex")
    names=["feature kernel","concatenated features","convex stack","network + residual"]
    data=[]
    for r in rr:
        for j,name in enumerate(names,1):
            vals=r[j].split(" / ")
            data.append([r[0],name]+vals+[r[5] if j==2 else "--"])
    write("layout_v2_replication.tex",tab("llrrrr",["seed","head",r"radiance [\%]",r"median [pp]",r"p95 [pp]",r"gain [pp]"],data,9,2.8))
    rr=rows("table_v2_stacks.tex")
    data=[]
    for r in rr:
        name=short(r[0]).replace("stack, mean relative norm","stack, mean relative norm").replace("stack, row-relative squared error","stack, row-relative square").replace("stack, unweighted component square","stack, unweighted square")
        data.append([name,r[1],r[2],stack(r[3]),r[4]])
    write("layout_v2_stacks.tex",tab("lrrrr",["head / fit",r"radiance [\%]",r"$\varepsilon_R$",r"\thead{constrained p95\\constrained p99}","raw p95"],data,9,2.7))
    rr=rows("table_v2_multikernel.tex")
    data=[[r[0].replace("kernel on features, ","features, ").replace("spectral mixture, four components","spectral mixture (4)").replace("coordinatewise selection","coordinate selection")]+r[1:] for r in rr]
    write("layout_v2_multikernel.tex",tab("lrrrr",["head",r"$Y_1$ [\%]",r"$Y_2$ [\%]",r"$Y_3$ [\%]",r"$Y_4$ [\%]"],data,9,3))
    rr=rows("table_v2_regsuite.tex")
    write("layout_v2_regsuite.tex",tab("lrrr",["head",r"\thead{alone\\component / radiance}",r"\thead{residual correction\\component / radiance}",r"\thead{feature kernel\\component / radiance}"],[[r[0]]+[stack(x) for x in r[1:]] for r in rr],9,3))
    # Full perturbation rows with explicit source-cohort names, not duplicate anonymous feature blocks.
    rr=rows("table_v2_perturbation.tex")
    labels=["state"]*14
    for f in sorted((ROOT/"results/ridge").glob("*_featpert.json")):
        d=json.loads(f.read_text()); seed=re.search(r"emit_s(\d+)_",f.name).group(1)
        labels += ["s"+seed+", $Y_"+d['component'][1:]+"$"]*len(d['systems'])
    if len(labels)!=len(rr): raise ValueError("Perturbation row provenance mismatch")
    for r,label in zip(rr,labels):
        r[0]=label
        r[1]=r[1].replace(r"pca\_features\_d","PCA features ").replace(r"pca\_inputs\_d","PCA inputs ").replace(r"nystrom\_m",r"Nystr\"om ").replace(r"gamma\_x",r"ridge $\times$").replace(r"concat\_all\_members","concatenation").replace(r"member1\_alone","member 1").replace(r"member2\_alone","member 2")
    cap=r'''Same-data perturbation diagnostics for Proposition~\ref{prop:perturb}. Movement is a Euclidean prediction change in retained coordinates. The four ratio columns are \emph{medians of entrywise bound/movement ratios}, not ratios of medians. The fourteen state-input rows use the direct flux $Y_2$ at seed 101 with 2,000 fitting rows; the feature rows use four component records at seed 101 and four at seed 104, each with 4,000 fitting and 1,000 query rows. The signed minimum eigenvalue is rounded: a displayed $-1.000$ does not assert exact equality to $-1$. A dash means the corresponding bound is not applicable.'''
    write("layout_v2_perturbation.tex",longtab("llrrrrrrr",["source", "perturbation",r"$\lambda_{\min}(B)$",r"$\|B\|$",r"\thead{median\\movement}",r"\thead{residual-action\\ratio}",r"\thead{signed-spectrum\\ratio}",r"\thead{$\|B\|<1$\\ratio}",r"\thead{ridge\\ratio}"],rr,cap,"tab:v2-perturbation",9,True))
    rr=rows("table_v2_ridge.tex")
    cap=r'''Ridge-path diagnostics, seed 101, 4,000 fitting and 1,000 query rows. The bias and noise factor refer to Proposition~\ref{prop:sensitivity}(iii); the factor multiplies a hypothetical noise variance and is not an estimate of simulator noise. Corrected and kernel-only test columns are mean relative errors of a physical spectral component, in percent. The final column uses retained PCA coordinates on the held-out half and compares same-half fitting with split-half fitting; it is a different metric and sample. No ridge is selected on these test values.'''
    write("layout_v2_ridge.tex",longtab("llrrrrrrrrr",["component","kernel",r"$\gamma$",r"$\mathrm{tr}S_\lambda$","bias",r"\thead{noise\\factor}",r"\thead{median\\$\|a_\lambda\|^2$}",r"\thead{median\\$\widetilde P_\lambda$}",r"\thead{corrected\\{[\%]}}",r"\thead{kernel only\\{[\%]}}",r"\thead{same / split half\\PCA error [\%]}"],rr,cap,"tab:v2-ridge",9,True))
    rr=rows("table_v2_synthetic.tex")
    write("layout_v2_synthetic.tex",tab("rrrrr",[r"$\beta$",r"\thead{average-family\\measured slope}",r"$\beta/(\beta+2)$",r"\thead{uniform-family\\measured slope}",r"\thead{analytic slope\\same ladder}"],[r[:5] for r in rr],9,6)+r"\par\bigskip"+"\n"+tab("rrrr",[r"$\beta$",r"\thead{uniform-family\\maximum relative gap}",r"\thead{profile-family\\maximum relative gap}","violations"],[[r[0]]+r[5:] for r in rr],9,8))
    rr=rows("table_v2_pkanrtm.tex")
    cap=r'''Matched correction-coefficient benchmark \cite{pkan}. The standard split uses 35,000 / 7,500 / 7,500 states. OOD test states exceed the 0.85 aerosol or water-vapor quantile; remaining states are split 85/15. Cells average three seeds or initializations; the reference rows are the published values. RMSE, MAE and SMAPE are pooled; $R^2$ is the uniform average over the three coefficients. Model keys: dkr, feature kernel; krr, input kernel; mlp, network; ens, ensemble; resid, residual correction; lowfi, the low-fidelity mean. The categorical inputs follow the benchmark protocol.'''
    write("layout_v2_pkanrtm.tex",longtab("lllrrrr",["split","inputs","head","RMSE","MAE",r"$R^2$",r"SMAPE [\%]"],rr,cap,"tab:v2-pkanrtm",9,True))
    rr=rows("table_v2_oco2.tex")
    cap=r'''OCO-2 selection comparison, seeds 0--2 on each of three bands. Each record uses 2,000 validation and 2,000 test rows. Both reported columns are \emph{mean relative norms} in percent; the stack fitting objectives are row-relative \emph{squared} errors. The radiance quadratic uses the exact affine reconstruction Gram matrix. Model keys: dkr, feature kernel; mean, trained network; ridge, linear readout; raw/ard, input kernels. Flat, radx and wnum are the three training losses. Selection is per coordinate, with the radiance variant using greedy coordinate updates, not exhaustive global search.'''
    write("layout_v2_oco2.tex",longtab("llrr",["band","head / rule",r"reduced error [\%]",r"radiance error [\%]"],rr,cap,"tab:v2-oco2",9,False))
    rr=rows("table_corpora.tex")
    def cname(n):
        return n.replace("Turbulent radiative layer","Radiative layer").replace("RT corrections, state inputs","RT coefficients, state").replace("RT corrections, multi-fidelity inputs","RT coefficients, +6S")
    a=[[cname(r[0])]+r[1:5] for r in rr]
    b=[[cname(r[0])]+r[5:9] for r in rr]
    c=[[cname(r[0])]+r[9:] for r in rr]
    text=r"\textbf{A. Configurations}\par\medskip"+"\n"+tab("lrrrr",["corpus",r"$n$",r"$d$",r"$q$","runs"],a,9,4)
    text+=r"\par\medskip\textbf{B. Reference, input kernels and network}\par\medskip"+"\n"+tab("lrrrr",["corpus","linear ridge","KRR",r"\thead{learned-metric\\KRR}","network"],b,9,3)
    text+=r"\par\medskip\textbf{C. Ensembles, corrections and combinations}\par\medskip"+"\n"+tab("lrrrr",["corpus","ensemble",r"\thead{network +\\residual KRR}","feature kernel","stack"],c,9,3)
    write("layout_corpora.tex",text)
    print("Formatted eleven supplementary/extended table layouts.")

if __name__ == "__main__":
    main()
