"""Tables for the training-target experiment (Section 6 of the manuscript), from the run records.

Inputs, under results/target_quality/:
  tq_s<seed>_<arm>_<config>.json              the campaign record (emit_campaign.py --training-policy)
  tq_s<seed>_<arm>_<config>_conditioned.json   the physical-domain scores (conditioned_reflectance.py)
with <arm> in raw, admissible, matched and <config> in w512, w2000. Only seeds with all three arms of a
configuration are used, so every paired difference is taken on one split and one machine. Writes:
  paper/table_tq_domain.tex    the raw arm: all-band and physical-domain reflectance tails and failures at the three
                               prespecified floors
  paper/table_tq_policy.tex    admissible and matched arms against raw: paired differences and counts of lower values
  paper/table_tq_reversal.tex  the convex stack against the kernel on features, in each arm
  paper/table_tq_runs.tex      seeds, machines and training counts
  results/target_quality/tq_summary.json   every number in the tables, per seed and pooled
Sample standard deviations use ddof=1. Reflectance errors are in percentage points. The floors are the protocol's
1e-12, 1e-3 and 1e-2 of the median positive training flux; they are selected by value, not by position.
"""
import glob
import json
import os
import re
import statistics as st

W = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RES = os.path.join(W, "results", "target_quality")
OUT = os.path.join(W, "paper")
ARMS = ("raw", "admissible", "matched")
FLOORS = (1e-12, 1e-3, 1e-2)
MACHINE = {s: "DGX" for s in range(101, 105)} | {s: "Kaggle" for s in range(105, 111)}   # addenda 1 and 2
NAMES = {"ridge3": "cubic ridge", "krr": "isotropic kernel", "ard": "input-scaled kernel", "dnn": "network",
         "dnn_corr": "network + residual kernel", "dkr": "kernel on features", "stack": "convex stack"}
ORDER = ("ridge3", "krr", "ard", "dnn", "dnn_corr", "dkr", "stack")
WIDTH = {"w512": "3$\\times$512", "w2000": "3$\\times$2000"}


def load(p):
    with open(p, encoding="utf-8") as f:
        return json.load(f)


def ms(values, digits):
    values = [v for v in values if v is not None]
    if not values:
        return "--"
    if len(values) == 1:
        return f"{values[0]:.{digits}f}"
    return f"{st.mean(values):.{digits}f}$\\pm${st.stdev(values):.{digits}f}"


def lower(values):
    values = [v for v in values if v is not None]
    return f"{sum(v < 0 for v in values)}/{len(values)}" if values else "--"


def collect():
    runs = {}
    for p in glob.glob(os.path.join(RES, "tq_s*_*_w*.json")):
        m = re.match(r"tq_s(\d+)_(raw|admissible|matched)_(w512|w2000)\.json$", os.path.basename(p))
        if not m:
            continue
        cond = p[:-5] + "_conditioned.json"
        if os.path.exists(cond):
            runs[(m.group(3), int(m.group(1)), m.group(2))] = (load(p), load(cond))
    complete = {}
    for cfg in ("w512", "w2000"):
        seeds = sorted({s for (c, s, a) in runs if c == cfg})
        complete[cfg] = [s for s in seeds if all((cfg, s, a) in runs for a in ARMS)]
    return runs, complete


def at_floor(cond, fam, floor):
    rows = [r for r in cond["results"][fam] if abs(r["threshold"] - floor) <= 1e-9 * floor]
    if len(rows) != 1:
        raise ValueError(f"{fam}: floor {floor} found {len(rows)} times")
    return rows[0]


def metrics(record, cond, fam):
    f = record["families"][fam]
    out = {"radiance": 100 * f["rel_l2_radiance"], "albedo": 100 * f["rel_l2_Y4"],
           "components": 100 * f["mean_rel_l2_components"],
           "allband_median": 100 * f["refl_mae_median"], "allband_p95": 100 * f["refl_p95_abs"]}
    for fl in FLOORS:
        c = at_floor(cond, fam, fl)
        key = f"{fl:g}"
        out[f"p95@{key}"] = 100 * c["p95_absolute_error"] if c["p95_absolute_error"] is not None else None
        out[f"median@{key}"] = 100 * c["median_absolute_error"] if c["median_absolute_error"] is not None else None
        out[f"coverage@{key}"] = 100 * c["retained_fraction_all_entries"]
        out[f"failed_pct@{key}"] = 100 * c["failed_inversions"] / c["retained_entries"]
        out[f"failed@{key}"] = c["failed_inversions"]
    return out


def tabular(cols, hdr, rows):
    body = "\\begin{tabular}{" + cols + "}\n\\toprule\n" + hdr + " \\\\\n\\midrule\n"
    return body + "\n".join(" & ".join(r) + " \\\\" for r in rows) + "\n\\bottomrule\n\\end{tabular}\n"


def write(name, seeds_note, text):
    with open(os.path.join(OUT, name), "w", encoding="utf-8", newline="\n") as f:
        f.write(f"% generated by code/make_tq_tables.py; seeds {seeds_note}\n" + text)


def main():
    runs, complete = collect()
    summary = {"seeds": complete, "machine": {str(s): MACHINE.get(s) for c in complete for s in complete[c]},
               "per_seed": {}, "pooled": {}, "coverage": {}}
    dom, pol, rev, cnt = [], [], [], []
    keys = [f"{fl:g}" for fl in FLOORS]
    for cfg in ("w512", "w2000"):
        seeds = complete[cfg]
        if not seeds:
            continue
        fams = [f for f in ORDER if f in runs[(cfg, seeds[0], "raw")][0]["families"]]
        for fam in fams:
            per = {s: {a: metrics(*runs[(cfg, s, a)], fam) for a in ARMS} for s in seeds}
            summary["per_seed"][f"{cfg}/{fam}"] = per
            raw = [per[s]["raw"] for s in seeds]
            row = [f"{NAMES[fam]} ({WIDTH[cfg]})", ms([r["radiance"] for r in raw], 3), ms([r["allband_p95"] for r in raw], 2)]
            for k in keys:
                row += [ms([r[f"failed_pct@{k}"] for r in raw], 2), ms([r[f"p95@{k}"] for r in raw], 2)]
            dom.append(row)
            for arm in ("admissible", "matched"):
                d = {m: [None if per[s][arm][m] is None or per[s]["raw"][m] is None else per[s][arm][m] - per[s]["raw"][m]
                         for s in seeds] for m in ("radiance", "albedo", "allband_p95", "p95@1e-12")}
                summary["pooled"][f"{cfg}/{fam}/{arm}-raw"] = d
                pol.append([f"{NAMES[fam]} ({WIDTH[cfg]})" if arm == "admissible" else "", arm,
                            ms(d["radiance"], 4), lower(d["radiance"]), ms(d["albedo"], 3),
                            ms(d["allband_p95"], 2), ms(d["p95@1e-12"], 2), lower(d["p95@1e-12"])])
        for k in keys:
            summary["coverage"][f"{cfg}/{k}"] = [runs[(cfg, s, "raw")][0] and metrics(*runs[(cfg, s, "raw")], "stack")[f"coverage@{k}"]
                                                 for s in seeds]
        if "stack" in fams and "dkr" in fams:
            for arm in ARMS:
                m = {s: (metrics(*runs[(cfg, s, arm)], "stack"), metrics(*runs[(cfg, s, arm)], "dkr")) for s in seeds}
                d_rad = [m[s][0]["radiance"] - m[s][1]["radiance"] for s in seeds]
                r_all = [m[s][0]["allband_p95"] / m[s][1]["allband_p95"] for s in seeds]
                r_phy = {k: [m[s][0][f"p95@{k}"] / m[s][1][f"p95@{k}"] for s in seeds
                             if m[s][0][f"p95@{k}"] and m[s][1][f"p95@{k}"]] for k in keys}
                summary["pooled"][f"{cfg}/stack_vs_dkr/{arm}"] = {"d_radiance": d_rad, "ratio_all_band": r_all,
                                                                  "ratio_physical": r_phy}
                rev.append([WIDTH[cfg] if arm == "raw" else "", arm, ms(d_rad, 4), lower(d_rad), ms(r_all, 2),
                            f"{sum(x > 1 for x in r_all)}/{len(r_all)}"] +
                           [ms(r_phy[k], 2) for k in keys] + [f"{sum(x > 1 for x in r_phy['1e-12'])}/{len(r_phy['1e-12'])}"])
        for s in seeds:
            tq = {a: runs[(cfg, s, a)][0]["target_quality"] for a in ARMS}
            cnt.append([WIDTH[cfg] if s == seeds[0] else "", str(s), MACHINE.get(s, "?"), f"{tq['raw']['retained_rows']:,}",
                        f"{tq['admissible']['retained_rows']:,}", f"{tq['matched']['retained_rows']:,}",
                        f"{runs[(cfg, s, 'raw')][0]['n_val']:,}", f"{runs[(cfg, s, 'raw')][0]['n_test']:,}"])
    note = f"w512 {complete.get('w512')} w2000 {complete.get('w2000')}"
    hdr = ("family & radiance [\\%] & \\thead{all bands\\\\$p_{95}$ [pp]}"
           + "".join(f" & \\thead{{$\\tau_0=10^{{{int(round(__import__('math').log10(fl)))}}}$\\\\failed [\\%]}} & $p_{{95}}$ [pp]"
                     for fl in FLOORS))
    write("table_tq_domain.tex", note, tabular("l" + "r" * 8, hdr, dom))
    hdr = ("family & arm & $\\Delta$ radiance [pp] & lower & $\\Delta$ albedo [\\%] & \\thead{$\\Delta$ all-band\\\\$p_{95}$ [pp]} "
           "& \\thead{$\\Delta$ physical\\\\$p_{95}$ [pp]} & lower")
    write("table_tq_policy.tex", note, tabular("llrrrrrr", hdr, pol))
    hdr = ("width & arm & \\thead{stack $-$ features\\\\radiance [pp]} & lower & \\thead{tail ratio\\\\all bands} & $>1$"
           + "".join(f" & \\thead{{tail ratio\\\\$\\tau_0=10^{{{int(round(__import__('math').log10(fl)))}}}$}}" for fl in FLOORS)
           + " & $>1$")
    write("table_tq_reversal.tex", note, tabular("llrrrrrrrr", hdr, rev))
    hdr = "width & seed & machine & raw & admissible & matched & validation & test"
    write("table_tq_runs.tex", note, tabular("llrrrrrr" if False else "lllrrrrr", hdr, cnt))
    with open(os.path.join(RES, "tq_summary.json"), "w", encoding="utf-8", newline="\n") as f:
        json.dump(summary, f, indent=1)
    print(json.dumps({"complete_seeds": complete, "domain_rows": len(dom), "policy_rows": len(pol),
                      "reversal_rows": len(rev), "run_rows": len(cnt)}))


if __name__ == "__main__":
    main()
